@Library('jenkinslib') _

pipeline {
    agent none
    environment {
        TRAINING_GIT_CREDS = credentials("TRAINING_GIT_CREDS")
        TRAINING_ART_CREDS = credentials("TRAINING_ART_CREDS")
    }
    parameters {
        string(name: 'lock_branch', defaultValue: 'develop', description: 'Branch in Lockfile Repository to use.')
    }
    options { skipDefaultCheckout() } 
    stages {
        stage('package_pipeline') {
            when { 
                triggeredBy 'BranchEventCause' 
                not { branch pattern: "pr-\\d+" }
                not { branch pattern: "develop" }
            }
            steps{
                conanPackagePipeline()
            }
            // stages {
                // stage('package_pipeline') {
                    // agent { 
                        // docker { 
                            // image 'conanio/gcc7' 
                            // args "--network ${TRAINING_DOCKER_NETWORK_NAME}"
                        // }
                    // }
                    // steps{
                        // conanPackagePipeline()
                    // }
                // }
            // }
        }
        // stage('product_pipeline'){
            // when { 
                // triggeredBy 'SCMTrigger' 
                // branch pattern: "PR-*"
            // }
            // steps {
                // withCleanWorkspace{
                    // withDemoDockerContainer{
                        // conanBuildFromLockfilesInDocker()
                    // }
                // }
            // }        
        // }
        // stage('promotion_pipeline'){
            // when { 
                // triggeredBy 'SCMTrigger' 
                // branch pattern: "develop"
            // }
            // steps {
                // withCleanWorkspace{
                    // withDemoDockerContainer{
                        // conanBuildFromLockfilesInDocker()
                    // }
                // }
            // }        
        // }
    }
}