pipeline {
    agent any
    environment {
        DEMO_GIT_CREDS = credentials("DEMO_GIT_CREDS")
        DEMO_ART_CREDS = credentials("DEMO_ART_CREDS")
        LOCKS_REPO = 'http://gitbucket/git/root/locks.git'
        LOCKS_BRANCH = 'develop'
        CI_SCRIPTS_REPO = 'http://gitbucket/git/root/ci_scripts.git'
        CI_SCRIPTS_BRANCH = 'develop'
    }
    parameters {
        string(name: 'lock_branch', defaultValue: '', description: 'Branch in Lockfile Repository to use.')
    }
    stages {
        stage('package_pipeline') {
            when { 
                triggeredBy 'SCMTrigger' 
                not {
                    branch pattern: "PR-\\d+"
                    branch pattern: "develop"
                    
                }
            }
            stages {
                stage('package_pipeline') {
                    steps{
                        sh printenv
                        sh git clone $CI_SCRIPTS_REPO -b $CI_SCRIPTS_BRANCH
                        sh ./ci_scripts/package_pipeline_init.sh
                        // sh ./ci_scripts/package_pipeline_run.sh
                    }
                }
            }
        }
        // stage('product_pipeline'){
            // when { 
                // triggeredBy 'SCMTrigger' 
                // branch pattern: "PR-*"
            // }
            // steps {
                // withCleanWorkspace{
                    // withDemoDockerContainer{
                        // conanBuildFromLockfilesInDocker()
                    // }
                // }
            // }        
        // }
        // stage('promotion_pipeline'){
            // when { 
                // triggeredBy 'SCMTrigger' 
                // branch pattern: "develop"
            // }
            // steps {
                // withCleanWorkspace{
                    // withDemoDockerContainer{
                        // conanBuildFromLockfilesInDocker()
                    // }
                // }
            // }        
        // }
    }
}