library("jenkinslib") _

pipeline {
    parameters {
        string(name: "LOCK_BRANCH", defaultValue: "develop", description: "Branch in Lockfile Repository to use.")
    }
    environment {
        TRAINING_GIT_CREDS = credentials("TRAINING_GIT_CREDS")
        TRAINING_ART_CREDS = credentials("TRAINING_ART_CREDS")
    }
    agent { label "master" }
    options { checkoutToSubdirectory("workspace")} 
    stages {
        stage("Package Pipeline") {
            when {
                not { changeRequest() }
                not { branch pattern: "conan_from_upstream" }
                not { branch pattern: "develop" }
            }
            steps{
                conanPackagePipeline()
            }
        }
        stage("Product Pipeline"){
            when {
                changeRequest()
            }
            steps{
                conanProductPipeline()
            }
        }
        stage("From Upstream"){
            when { 
                triggeredBy "UpstreamCause" 
                branch pattern: "conan_from_upstream"
            }
            steps{
                conanFromUpstream()
            }
        }
        stage("Promotion Pipeline"){
            when {
                branch pattern: "develop"
                not { changeRequest() }
            }
            steps{
                conanPromotionPipeline()
            }
        }
    }
}
