library('jenkinslib') _

pipeline {
    agent { label 'master' }
    parameters {
        string(name: 'LOCK_BRANCH', defaultValue: 'develop', description: 'Branch in Lockfile Repository to use.')
    }
    environment {
        TRAINING_GIT_CREDS = credentials("TRAINING_GIT_CREDS")
        TRAINING_ART_CREDS = credentials("TRAINING_ART_CREDS")
    }
    options { checkoutToSubdirectory("workspace")} 
    stages {
        stage('Package Pipeline') {
            when {
                not { changeRequest() }
                not { branch pattern: "develop" }
                not { triggeredBy 'UpstreamCause' }
            }
            steps{
                conanPackagePipeline()
            }
        }
        stage('Product Pipeline'){
            when {
                changeRequest()
                not { branch pattern: "develop" }
            }
            steps{
                conanProductPipeline()
            }
        }
        stage('From Upstream'){
            when { 
                triggeredBy 'UpstreamCause' 
                branch pattern: 'conan_from_upstream'
            }
            steps{
                conanFromUpstream()
            }
        }
        stage('Promotion Pipeline'){
            when {
                triggeredBy 'SCMTrigger'
                branch pattern: "develop"
                not { changeRequest() }
            }
            steps{
                conanPromotionPipeline()
            }
        }
    }
}
